if(DEFINED USE_CONCURRENT_QUEUE)
    include_directories(BEFORE SYSTEM "${USE_CONCURRENT_QUEUE}")
else()
    include_directories(BEFORE SYSTEM "${CMAKE_CURRENT_LIST_DIR}/../../deps/concurrentqueue")
endif()
