# Find: -lncbi-ngs-c++ -lncbi-ngs -lngs-c++ -lncbi-vdb
include("${LIBCEU_CMAKE_COLLECTION_DIR}/libcmake/enhanced_find.cmake")
if(BUILD_SHARED_LIBS)
    if(NOT TARGET CEU_CM_EFL::libncbi_ngs_cxx)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE libncbi_ngs_cxx LINKER_FLAG ncbi-ngs-c++)
    endif()
    if(NOT TARGET CEU_CM_EFL::libncbi_ngs)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE libncbi_ngs LINKER_FLAG ncbi-ngs)
    endif()
    if(NOT TARGET CEU_CM_EFL::libngs_cxx)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE libngs_cxx LINKER_FLAG ngs-c++)
    endif()
    if(NOT TARGET CEU_CM_EFL::libncbi_vdb)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE libncbi_vdb LINKER_FLAG ncbi-vdb)
    endif()
else()
    if(NOT TARGET CEU_CM_EFL::libncbi_ngs_cxx)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE STATIC libncbi_ngs_cxx LINKER_FLAG ncbi-ngs-c++)
    endif()
    if(NOT TARGET CEU_CM_EFL::libncbi_ngs)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE STATIC libncbi_ngs LINKER_FLAG ncbi-ngs)
    endif()
    if(NOT TARGET CEU_CM_EFL::libngs_cxx)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE STATIC libngs_cxx LINKER_FLAG ngs-c++)
    endif()
    if(NOT TARGET CEU_CM_EFL::libncbi_vdb)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE STATIC libncbi_vdb LINKER_FLAG ncbi-vdb)
    endif()
endif()
if(NOT TARGET CEU_CM_EFL::libncbi_ngs_cxx)
    message(FATAL_ERROR "Could not find -lncbi-ngs-c++")
endif()
if(NOT TARGET CEU_CM_EFL::libncbi_ngs)
    message(FATAL_ERROR "Could not find -lncbi-ngs")
endif()
if(NOT TARGET CEU_CM_EFL::libngs_cxx)
    message(FATAL_ERROR "Could not find -lngs-c++")
endif()
if(NOT TARGET CEU_CM_EFL::libncbi_vdb)
    message(FATAL_ERROR "Could not find -lncbi-vdb")
endif()
set(ART_MODERN_LINK_LIBS ${ART_MODERN_LINK_LIBS} CEU_CM_EFL::libncbi_ngs_cxx CEU_CM_EFL::libncbi_ngs
                         CEU_CM_EFL::libngs_cxx CEU_CM_EFL::libncbi_vdb)
