# Find: -lncbi-ngs
include("${LIBCEU_CMAKE_COLLECTION_DIR}/libcmake/enhanced_find.cmake")
if(BUILD_SHARED_LIBS)
    if(NOT TARGET CEU_CM_EFL::libncbi_ngs)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE libncbi_ngs LINKER_FLAG ncbi-ngs)
    endif()
else()
    if(NOT TARGET CEU_CM_EFL::libncbi_ngs)
        ceu_cm_enhanced_find_library(OUTPUT_VARIABLE STATIC libncbi_ngs LINKER_FLAG ncbi-ngs)
    endif()
endif()
if(NOT TARGET CEU_CM_EFL::libncbi_ngs)
    message(FATAL_ERROR "Could not find -lncbi-ngs")
endif()
set(ART_MODERN_LINK_LIBS ${ART_MODERN_LINK_LIBS} CEU_CM_EFL::libncbi_ngs)
