unset(WITH_MIMALLOC)
unset(WITH_JEMALLOC)

if("${USE_MALLOC}" STREQUAL AUTO)
    find_package(mimalloc)
    if(mimalloc_FOUND)
        set(WITH_MIMALLOC ON)
        if(BUILD_SHARED_LIBS)
            set(ART_MODERN_LINK_LIBS ${ART_MODERN_LINK_LIBS} mimalloc)
        else()
            set(ART_MODERN_LINK_LIBS ${ART_MODERN_LINK_LIBS} mimalloc-static)
        endif()
    else()
        # Find jemalloc TODO
    endif()
elseif("${USE_MALLOC}" STREQUAL MIMALLOC)
    find_package(mimalloc REQUIRED)
    set(WITH_MIMALLOC ON)
    if(BUILD_SHARED_LIBS)
        set(ART_MODERN_LINK_LIBS ${ART_MODERN_LINK_LIBS} mimalloc)
    else()
        set(ART_MODERN_LINK_LIBS ${ART_MODERN_LINK_LIBS} mimalloc-static)
    endif()
elseif("${USE_MALLOC}" STREQUAL JEMALLOC)
    # Find jemalloc TODO
elseif("${USE_MALLOC}" STREQUAL NOP)
    # Do nothing!
else()
    message(FATAL_ERROR "Unknown USE_MALLOC: ${USE_MALLOC}. Sgould be one of AUTO, MIMALLOC, JEMALLOC, and NOP")
endif()
