unset(USE_WALKER_QUALGEN)
unset(USE_BTREE_MAP_QUALGEN)
unset(USE_STL_QUALGEN)

if(DEFINED USE_BTREE_MAP)
    message(WARNING "-DUSE_BTREE_MAP will be deprecated; Use -DUSE_QUAL_GEN=BTREE_MAP instead.")
    if(DEFINED USE_QUAL_GEN)
        message(WARNING "-DUSE_BTREE_MAP and -DUSE_QUAL_GEN cannot be set at the same time; Ignore -DUSE_BTREE_MAP")
    else()
        if(USE_BTREE_MAP)
            set(USE_QUAL_GEN BTREE_MAP)
        endif()
    endif()
endif()

if(NOT DEFINED USE_QUAL_GEN)
    set(USE_QUAL_GEN WALKER)
endif()

if("${USE_QUAL_GEN}" STREQUAL "WALKER")
    set(USE_WALKER_QUALGEN ON)
elseif ("${USE_QUAL_GEN}" STREQUAL "BTREE_MAP")
    set(USE_BTREE_MAP_QUALGEN ON)
elseif ("${USE_QUAL_GEN}" STREQUAL "STL")
    set(USE_STL_QUALGEN ON)
else()
    message(FATAL_ERROR "Unknown USE_QUAL_GEN: ${USE_QUAL_GEN}. Should be one of WALKER, BTREE_MAP, and STL")
endif ()
