unset(USE_STL_RANDOM)
unset(USE_GSL_RANDOM)
unset(USE_BOOST_RANDOM)
unset(USE_ONEMKL_RANDOM)
unset(WITH_GSL)
unset(WITH_ONEMKL)

if(NOT DEFINED USE_RANDOM_GENERATOR)
    set(USE_RANDOM_GENERATOR STL)
endif()

if("${USE_RANDOM_GENERATOR}" STREQUAL "STL")
    set(USE_STL_RANDOM ON)
elseif("${USE_RANDOM_GENERATOR}" STREQUAL "GSL")
    find_package(GSL REQUIRED)
    set(USE_GSL_RANDOM ON)
    set(WITH_GSL ON)
    set(ART_MODERN_LINK_LIBS ${ART_MODERN_LINK_LIBS} GSL::gsl)
    include_directories(${GSL_INCLUDE_DIRS})
elseif("${USE_RANDOM_GENERATOR}" STREQUAL "BOOST")
    set(USE_BOOST_RANDOM ON)
elseif("${USE_RANDOM_GENERATOR}" STREQUAL "PCG")
    set(USE_PCG_RANDOM ON)
    include_directories("${CMAKE_CURRENT_LIST_DIR}/../deps/pcg-cpp-0.98/include")
elseif("${USE_RANDOM_GENERATOR}" STREQUAL "ONEMKL")
    find_package(MKL REQUIRED)
    set(USE_ONEMKL_RANDOM ON)
    set(WITH_ONEMKL ON)
    include_directories(${MKL_INCLUDE} ${SYCL_INCLUDE_DIR})
    set(ART_MODERN_LINK_LIBS ${ART_MODERN_LINK_LIBS} MKL::MKL)
else()
    message(
        FATAL_ERROR
            "Variable USE_RANDOM_GENERATOR should be set to one of STL, GSL, BOOST or ONEMKL. Current: ${USE_RANDOM_GENERATOR}"
    )
endif()
