set(CMAKE_C_COMPILER   clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_LINKER      lld)
set(CMAKE_AR          llvm-ar)
set(CMAKE_NM          llvm-nm)
set(CMAKE_RANLIB      llvm-ranlib)
set(CMAKE_C_FLAGS     "${CMAKE_C_FLAGS} -fuse-ld=lld")
set(CMAKE_CXX_FLAGS   "${CMAKE_CXX_FLAGS} -fuse-ld=lld")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
