#pragma once

#define HIGHEST_QUAL 80
#define MAX_QUAL 93
#define MIN_QUAL 0

#define MAX_DIST_NUMBER 1000000
#define DEFAULT_INS_RATE_1 0.00009
#define DEFAULT_DEL_RATE_1 0.00011
#define DEFAULT_INS_RATE_2 0.00015
#define DEFAULT_DEL_RATE_2 0.00023
#define DEFAULT_MAX_INDEL (-1)
#define DEFAULT_MAX_NUM_N (-1)

enum class ART_LIB_CONST_MODE {
    SE, PE, MP
};
#define ART_LIB_CONST_MODE_SE "se"
#define ART_LIB_CONST_MODE_PE "pe"
#define ART_LIB_CONST_MODE_MP "mp"

